# Generated by Django 5.1.1 on 2024-10-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yacht",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(default="default_type", max_length=50)),
                ("description", models.TextField()),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Turkey", "Turkey"),
                            ("France", "France"),
                            ("Spain", "Spain"),
                        ],
                        default="Turkey",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "card_image",
                    models.ImageField(blank=True, null=True, upload_to="yachts/cards/"),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="yachts/details/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YachtImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="yachts/images/")),
                (
                    "yacht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="yachts.yacht",
                    ),
                ),
            ],
        ),
    ]
