# Generated by Django 5.1.1 on 2024-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yacht",
            name="detail_image",
        ),
        migrations.AddField(
            model_name="yacht",
            name="detail_image1",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
        migrations.AddField(
            model_name="yacht",
            name="detail_image2",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
        migrations.AddField(
            model_name="yacht",
            name="detail_image3",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
        migrations.DeleteModel(
            name="YachtImage",
        ),
    ]
