# Generated by Django 5.1.1 on 2024-10-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yachts/'),
        ),
        migrations.AddField(
            model_name='yacht',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='type',
            field=models.CharField(default='default_type', max_length=50),
        ),
    ]
