# Generated by Django 5.1.1 on 2024-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0003_remove_yacht_sku_alter_yacht_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yachts/cards/'),
        ),
    ]
