# Generated by Django 5.1.1 on 2024-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0004_alter_yacht_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='country',
            field=models.CharField(choices=[('Turkey', 'Turkey'), ('France', 'France'), ('Spain', 'Spain')], default='Turkey', max_length=50),
        ),
    ]
