# Generated by Django 5.1.1 on 2024-10-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0006_yacht_detail_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yacht',
            old_name='image',
            new_name='card_image',
        ),
    ]
