# Generated by Django 5.1.1 on 2024-10-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yachts', '0007_rename_image_yacht_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='detail_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
