# Generated by Django 5.1.1 on 2024-10-20 21:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0008_yacht_detail_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yacht",
            name="card_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="yacht",
            name="detail_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
