# Generated by Django 5.1.1 on 2024-10-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0009_alter_yacht_card_image_alter_yacht_detail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yacht",
            name="card_image",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/cards/"),
        ),
        migrations.AlterField(
            model_name="yacht",
            name="detail_image",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
    ]
