# Generated by Django 5.1.1 on 2024-10-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0010_alter_yacht_card_image_alter_yacht_detail_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yacht",
            name="available",
        ),
    ]
