# Generated by Django 5.1.1 on 2024-10-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0011_remove_yacht_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="YachtImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="yachts/images/")),
                (
                    "yacht",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="yachts.yacht",
                    ),
                ),
            ],
        ),
    ]
