# Generated by Django 5.1.1 on 2024-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0012_yachtimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yacht",
            old_name="detail_image",
            new_name="detail_image1",
        ),
        migrations.RemoveField(
            model_name="yacht",
            name="detail_image_url",
        ),
        migrations.AddField(
            model_name="yacht",
            name="detail_image2",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
        migrations.AddField(
            model_name="yacht",
            name="detail_image3",
            field=models.ImageField(blank=True, null=True, upload_to="yachts/details/"),
        ),
        migrations.DeleteModel(
            name="YachtImage",
        ),
    ]
