# Generated by Django 5.1.1 on 2024-10-21 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yachts", "0014_alter_yacht_card_image_alter_yacht_detail_image1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="yacht",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="yacht",
            name="card_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="card image"
            ),
        ),
        migrations.AlterField(
            model_name="yacht",
            name="detail_image1",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="detail image 1"
            ),
        ),
        migrations.AlterField(
            model_name="yacht",
            name="detail_image2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="detail image 2"
            ),
        ),
        migrations.AlterField(
            model_name="yacht",
            name="detail_image3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="detail image 3"
            ),
        ),
    ]
