# Generated by Django 5.1.1 on 2024-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
