# Generated by Django 5.1.1 on 2024-10-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_review_helpful_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='helpful_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reported',
        ),
    ]
